apiVersion: v1
kind: Pod
metadata:
  name: flask-pod
  labels:
    app: flask-lumberTakeoff
spec:
  containers:
  - name: flask
    image: ericvim/lumber-takeoff:v2.3
    ports:
    - containerPort: 5000
